name: KL-PHOTO
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5573551966808736
title: 'Kristian Lund '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f191a'
    - '#938f39'
    - '#4a4d56'
    - '#b7a791'
    - '#d0cbc0'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
