typography_spectrum: 0.5573551966808736
color:
  brandColors:
    - '#1f191a'
    - '#938f39'
    - '#4a4d56'
    - '#b7a791'
    - '#d0cbc0'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: KL-PHOTO
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Kristian Lund '
purpose: []
